# Generated by Django 3.0.2 on 2020-01-19 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('somedjangoapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='question_test',
            new_name='question_text',
        ),
    ]
